Name: Spacy v3 Cuda
Version: 1.0
Owner: Vimal Menon
DataFormat: CoNLL2003
RunOn: Docker
Details:
  Image: False
  Port: 7707/tcp # 22/TCP 
  HostIP: 0.0.0.0
  Debug: True
  DockerHost: localhost
  DockerHostPort: 2375
  Runtime: nvidia
AlgoFrom: Git #(local/remote)
AlgoDetails:
  Path: https://github.com/astutic/acharya-spacy.git
  Branch: setup
  Auth: None #(http/ssh/None)
  DockerfilePath: Dockerfile
  ConfigPath: config.yaml
  AlgoOutput:
    - /models
  RestoreOutput: True
  Logs:
    - /root/parse_ner.log
  