Name: Spacy PreTrained
Version: 1.0
Owner: Astutic AI
DataFormat: Conll2003
RunOn: Docker
Details:
  Image: False
  Port: 7707/tcp # 22/TCP 
  HostIP: 0.0.0.0
  Debug: True
  DockerHost: localhost
  DockerHostPort: 2375
AlgoFrom: Git #(local/remote)
AlgoDetails:
  Path: https://github.com/astutic/acharya-spacy.git
  Branch: PreModelEvalCPU
  Auth: None #(http/ssh/None)
  DockerfilePath: Dockerfile
  ConfigPath: config.yaml
  AlgoOutput:
    - /root/.cache
    - /root/NEREntities.json
  RestoreOutput: True
  Logs:
    - /root/parse_ner.log
    
