title: Spacy Algo config for Acharya
owner: Astutic AI
author: VM
train:
        cmd: /bin/sh train.sh
        type: cmd
        input: data/trainfile.conll
        output: stdout
eval:
        cmd: python3 evaluate_model.py
        type: service
        input: "tcp::5566"
        output: "tcp::5566"
